runtime: nodejs18
service: default

env_variables:
  JWT_SECRET: "projects/256750491849/secrets/JWT_SECRET/versions/1"
  DATABASE_URL: "projects/256750491849/secrets/DATABASE_URL/versions/1"
  DIRECT_URL: "projects/256750491849/secrets/DIRECT_URL/versions/1"
  GOOGLE_REFRESH_TOKEN: "projects/256750491849/secrets/GOOGLE_REFRESH_TOKEN/versions/1"
  GOOGLE_CLIENT_ID: "projects/256750491849/secrets/GOOGLE_CLIENT_ID/versions/1"
  GOOGLE_CLIENT_SECRET: "projects/256750491849/secrets/GOOGLE_CLIENT_SECRET/versions/1"
  GOOGLE_SENDER_EMAIL: "projects/256750491849/secrets/GOOGLE_SENDER_EMAIL/versions/1"
