runtime: nodejs18
service: default

env_variables:
  JWT_SECRET: ${_JWT_SECRET}
  DATABASE_URL: ${_DATABASE_URL}
  DIRECT_URL: ${_DIRECT_URL}
  GOOGLE_REFRESH_TOKEN: ${_GOOGLE_REFRESH_TOKEN}
  GOOGLE_CLIENT_ID: ${_GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${_GOOGLE_CLIENT_SECRET}
  GOOGLE_SENDER_EMAIL: ${_GOOGLE_SENDER_EMAIL}
